spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3306/qr_core
    password: example
    username: root

  flyway:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://0.0.0.0:3306/qr_core?useSSL=false
    password: example
    user: root
    baseline-on-migrate: true


  jpa:
    hibernate:
      use-new-id-generator-mappings: false

spring.session.jdbc.initialize-schema: always

server:
  port: 8082