spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3306/qr_core
    password: example
    username: root

  flyway:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://0.0.0.0:3306/qr_core?useSSL=false
    password: example
    user: root
    baseline-on-migrate: true

spring.session.jdbc.initialize-schema: always
#spring.jpa.hibernate.ddl-auto: validate

server:
  port: 8082